name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    environment: MyTestEnv
    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          echo Running! 5
          echo "Hello ${{vars.FOOBAR}}"
          find ./ -name 'hello.txt' -exec cp "{}" ~/ \;
