name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    environment: MyTestEnv
    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          echo "Hello ${{vars.FOOBAR}}"
          scp ./hello.txt ${{secrets.UTILITY_SERVER_CONN}}:~/
